// ===========================================================================
// KUSSALA V2 — Supabase Database Types
// ===========================================================================
// This file is auto-generated by: npm run db:types
// (supabase gen types typescript --local > src/types/database.ts)
//
// DO NOT EDIT MANUALLY — regenerate after schema changes.
// ===========================================================================

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          first_name: string;
          last_name: string;
          username: string | null;
          date_of_birth: string | null;
          whatsapp: string;
          phone: string | null;
          city: string;
          neighborhood: string | null;
          job_type: string;
          experience: string | null;
          interests: string[];
          user_type: "seeker" | "employer";
          is_active: boolean;
          subscription_paid: boolean;
          expiry_date: string | null;
          avatar_url: string | null;
          linkedin_url: string;
          facebook_url: string;
          instagram_url: string;
          github_url: string;
          cv_path: string | null;
          cv_filename: string | null;
          cv_size: number | null;
          cv_public: boolean;
          // ── Pôle Étudiant ────────────────────────────────────────────────
          is_student: boolean;
          school_name: string;
          field_of_study: string;
          study_level: string;
          school_year: string;
          internship_open: boolean;
          alternance_open: boolean;
          internship_start: string | null;
          internship_duration: string;
          internship_mode: string;
          student_description: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          first_name: string;
          last_name?: string;
          username?: string | null;
          date_of_birth?: string | null;
          whatsapp: string;
          phone?: string | null;
          city: string;
          neighborhood?: string | null;
          job_type?: string;
          experience?: string | null;
          interests?: string[];
          user_type: "seeker" | "employer";
          is_active?: boolean;
          subscription_paid?: boolean;
          expiry_date?: string | null;
          avatar_url?: string | null;
          linkedin_url?: string;
          facebook_url?: string;
          instagram_url?: string;
          github_url?: string;
          cv_path?: string | null;
          cv_filename?: string | null;
          cv_size?: number | null;
          cv_public?: boolean;
          is_student?: boolean;
          school_name?: string;
          field_of_study?: string;
          study_level?: string;
          school_year?: string;
          internship_open?: boolean;
          alternance_open?: boolean;
          internship_start?: string | null;
          internship_duration?: string;
          internship_mode?: string;
          student_description?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          first_name?: string;
          last_name?: string;
          username?: string | null;
          date_of_birth?: string | null;
          whatsapp?: string;
          phone?: string | null;
          city?: string;
          neighborhood?: string | null;
          job_type?: string;
          experience?: string | null;
          interests?: string[];
          user_type?: "seeker" | "employer";
          is_active?: boolean;
          subscription_paid?: boolean;
          expiry_date?: string | null;
          avatar_url?: string | null;
          linkedin_url?: string;
          facebook_url?: string;
          instagram_url?: string;
          github_url?: string;
          cv_path?: string | null;
          cv_filename?: string | null;
          cv_size?: number | null;
          cv_public?: boolean;
          is_student?: boolean;
          school_name?: string;
          field_of_study?: string;
          study_level?: string;
          school_year?: string;
          internship_open?: boolean;
          alternance_open?: boolean;
          internship_start?: string | null;
          internship_duration?: string;
          internship_mode?: string;
          student_description?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      jobs: {
        Row: {
          id: string;
          user_id: string;
          first_name: string;
          age: number;
          whatsapp: string | null;
          city: string;
          neighborhood: string | null;
          job_type: string;
          experience: string | null;
          user_type: "seeker" | "employer";
          is_active: boolean;
          publication_status:
            | "draft"
            | "pending"
            | "published"
            | "rejected";
          created_at: string;
          expires_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          first_name: string;
          age: number;
          whatsapp?: string | null;
          city: string;
          neighborhood?: string | null;
          job_type: string;
          experience?: string | null;
          user_type: "seeker" | "employer";
          is_active?: boolean;
          publication_status?:
            | "draft"
            | "pending"
            | "published"
            | "rejected";
          created_at?: string;
          expires_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          first_name?: string;
          age?: number;
          whatsapp?: string | null;
          city?: string;
          neighborhood?: string | null;
          job_type?: string;
          experience?: string | null;
          user_type?: "seeker" | "employer";
          is_active?: boolean;
          publication_status?:
            | "draft"
            | "pending"
            | "published"
            | "rejected";
          expires_at?: string;
        };
        Relationships: [];
      };
      payments: {
        Row: {
          id: string;
          user_id: string;
          amount: number;
          method: "orange" | "telecel";
          status: "pending" | "completed" | "failed";
          reference: string;
          transaction_id: string | null;
          phone_number: string;
          created_at: string;
          processed_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          amount?: number;
          method: "orange" | "telecel";
          status?: "pending" | "completed" | "failed";
          reference: string;
          transaction_id?: string | null;
          phone_number: string;
          created_at?: string;
          processed_at?: string | null;
        };
        Update: {
          status?: "pending" | "completed" | "failed";
          transaction_id?: string | null;
          processed_at?: string | null;
        };
        Relationships: [];
      };
      messages: {
        Row: {
          id: string;
          from_user_id: string | null;
          to_user_id: string;
          subject: string;
          content: string;
          is_read: boolean;
          is_starred: boolean;
          is_archived: boolean;
          category: "job_inquiry" | "job_offer" | "general";
          created_at: string;
        };
        Insert: {
          id?: string;
          from_user_id?: string | null;
          to_user_id: string;
          subject: string;
          content: string;
          is_read?: boolean;
          is_starred?: boolean;
          is_archived?: boolean;
          category?: "job_inquiry" | "job_offer" | "general";
          created_at?: string;
        };
        Update: {
          is_read?: boolean;
          is_starred?: boolean;
          is_archived?: boolean;
        };
        Relationships: [];
      };
      job_types: {
        Row: {
          id: string;
          name: string;
          category: string;
          description: string | null;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          category: string;
          description?: string | null;
          is_active?: boolean;
          created_at?: string;
        };
        Update: {
          name?: string;
          category?: string;
          description?: string | null;
          is_active?: boolean;
        };
        Relationships: [];
      };
      info_contents: {
        Row: {
          id: string;
          type: "formation" | "stage" | "conseil";
          title: string;
          content: string;
          author: string | null;
          category: string | null;
          location: string | null;
          duration: string | null;
          level: string | null;
          is_published: boolean;
          featured: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          type: "formation" | "stage" | "conseil";
          title: string;
          content: string;
          author?: string | null;
          category?: string | null;
          location?: string | null;
          duration?: string | null;
          level?: string | null;
          is_published?: boolean;
          featured?: boolean;
          created_at?: string;
        };
        Update: {
          type?: "formation" | "stage" | "conseil";
          title?: string;
          content?: string;
          author?: string | null;
          category?: string | null;
          location?: string | null;
          duration?: string | null;
          level?: string | null;
          is_published?: boolean;
          featured?: boolean;
        };
        Relationships: [];
      };
      admin_users: {
        Row: {
          id: string;
          email: string;
          password_hash: string;
          role: "superadmin" | "moderator";
          totp_secret: string | null;
          mfa_enabled: boolean;
          is_active: boolean;
          last_login_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          email: string;
          password_hash: string;
          role?: "superadmin" | "moderator";
          totp_secret?: string | null;
          mfa_enabled?: boolean;
          is_active?: boolean;
          last_login_at?: string | null;
          created_at?: string;
        };
        Update: {
          email?: string;
          password_hash?: string;
          role?: "superadmin" | "moderator";
          totp_secret?: string | null;
          mfa_enabled?: boolean;
          is_active?: boolean;
          last_login_at?: string | null;
        };
        Relationships: [];
      };
      sectors: {
        Row: {
          id: string;
          name: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          created_at?: string;
        };
        Update: {
          name?: string;
        };
        Relationships: [];
      };
      subscriptions: {
        Row: {
          id: string;
          user_id: string;
          plan: "freemium" | "premium";
          status: "active" | "inactive" | "cancelled";
          start_date: string;
          end_date: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          plan?: "freemium" | "premium";
          status?: "active" | "inactive" | "cancelled";
          start_date: string;
          end_date: string;
          created_at?: string;
        };
        Update: {
          plan?: "freemium" | "premium";
          status?: "active" | "inactive" | "cancelled";
          start_date?: string;
          end_date?: string;
        };
        Relationships: [];
      };
      audit_logs: {
        Row: {
          id: string;
          user_id: string | null;
          action: string;
          details: Json;
          ip_address: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          action: string;
          details?: Json;
          ip_address?: string | null;
          created_at?: string;
        };
        Update: Record<string, never>;
        Relationships: [];
      };
      webhooks: {
        Row: {
          id: string;
          event: string;
          payload: Json;
          signature: string;
          processed: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          event: string;
          payload: Json;
          signature: string;
          processed?: boolean;
          created_at?: string;
        };
        Update: {
          processed?: boolean;
        };
        Relationships: [];
      };
      sessions: {
        Row: {
          id: string;
          user_id: string;
          token: string;
          expires_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          token: string;
          expires_at: string;
          created_at?: string;
        };
        Update: {
          expires_at?: string;
        };
        Relationships: [];
      };
      password_resets: {
        Row: {
          id: string;
          user_id: string;
          token: string;
          expires_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          token: string;
          expires_at: string;
          created_at?: string;
        };
        Update: {
          expires_at?: string;
        };
        Relationships: [];
      };
      email_verifications: {
        Row: {
          id: string;
          user_id: string;
          token: string;
          expires_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          token: string;
          expires_at: string;
          created_at?: string;
        };
        Update: {
          expires_at?: string;
        };
        Relationships: [];
      };
      otp_codes: {
        Row: {
          id: string;
          user_id: string;
          code: string;
          expires_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          code: string;
          expires_at: string;
          created_at?: string;
        };
        Update: {
          expires_at?: string;
        };
        Relationships: [];
      };
      admin_messages: {
        Row: {
          id: string;
          user_id: string | null;
          subject: string;
          content: string;
          is_read: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          subject: string;
          content: string;
          is_read?: boolean;
          created_at?: string;
        };
        Update: {
          is_read?: boolean;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: {
      is_premium: {
        Args: { uid: string };
        Returns: boolean;
      };
      count_active_jobs: {
        Args: { uid: string };
        Returns: number;
      };
      check_email_available: {
        Args: { email_to_check: string };
        Returns: boolean;
      };
      check_phone_available: {
        Args: { phone_to_check: string };
        Returns: boolean;
      };
    };
    Enums: {
      user_type: "seeker" | "employer";
      payment_method: "orange" | "telecel";
      payment_status: "pending" | "completed" | "failed";
      publication_status: "draft" | "pending" | "published" | "rejected";
      subscription_plan: "freemium" | "premium";
      subscription_status: "active" | "inactive" | "cancelled";
      admin_role: "superadmin" | "moderator";
    };
  };
};
